baseURL = "https://joshuarubin.github.io/jawa/"
languageCode = "en-us"
title = "Joshua Rubin"
theme = "simple-hugo-theme"
copyright = "© {year} — <a href=\"https://creativecommons.org/licenses/by/4.0/\">Some rights reserved</a>"
enableGitInfo = true
canonifyURLs = true
# googleAnalytics = "UA-123-45"

enableRobotsTXT = true

paginate = 3
paginatePath = "page"

pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=table"
# pygmentsStyle = "native"
pygmentsUseClasses = true

[params]
  description = "Musings. Code. Mostly code."
  images = ["img/avatar.jpg"]
  title = "Joshua Rubin"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[menu]
  [[menu.main]]
    url = "/posts/"
    name = "blog"
    weight = 1
  [[menu.main]]
    url = "/about/"
    name = "about"
    weight = 2
  [[menu.main]]
    url = "/contact/"
    name = "contact"
    weight = 3

  [[menu.footer]]
    url = "https://github.com/joshuarubin"
    name = "GitHub"
    weight = 1
  [[menu.footer]]
    url = "/posts/index.xml"
    name = "RSS"
    weight = 2
  # [[menu.footer]]
  #   url = "mailto:foo@bar.com"
  #   name = "Contact"
  #   weight = 3

[permalinks]
  posts = "/posts/:year/:month/:title/"
