baseURL = "https://jrubin.io/"
languageCode = "en-us"
title = "Joshua Rubin"
theme = "simple-hugo-theme"
copyright = "© {year} — <a href=\"https://creativecommons.org/licenses/by/4.0/\">Some rights reserved</a>"
enableGitInfo = true
canonifyURLs = true

enableRobotsTXT = true
enableEmoji = true

paginate = 3
paginatePath = "page"

pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=table"
pygmentsUseClasses = true

[params]
  fathom = "LLTGF"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[menu]
  [[menu.main]]
    url = "/about/"
    name = "about"
    weight = 1
  [[menu.main]]
    url = "/contact/"
    name = "contact"
    weight = 2

  [[menu.footer]]
    url = "https://github.com/joshuarubin"
    name = "GitHub"
    weight = 1
  [[menu.footer]]
    url = "/posts/index.xml"
    name = "RSS"
    weight = 2

[permalinks]
  posts = "/posts/:year/:month/:title/"
