baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "simple-hugo-theme"
copyright = "© 2019 — Some Author — All rights reserved."
# googleAnalytics = "UA-123-45"

enableRobotsTXT = true

paginate = 3
paginatePath = "page"

pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=table"
# pygmentsStyle = "native"
pygmentsUseClasses = true

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  [[menu.main]]
    url = "/posts/"
    name = "blog"
    weight = 1
  [[menu.main]]
    url = "/about/"
    name = "about"
    weight = 2
  [[menu.main]]
    url = "/contact/"
    name = "contact"
    weight = 3

  [[menu.footer]]
    url = "https://github.com/Xzya"
    name = "GitHub"
    weight = 1
  [[menu.footer]]
    url = "/posts/index.xml"
    name = "RSS"
    weight = 2
  [[menu.footer]]
    url = "mailto:foo@bar.com"
    name = "Contact"
    weight = 3

[permalinks]
  posts = "/posts/:year/:month/:title/"
